# This is a basic workflow to help you get started with Actions

name: thirdweb-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "master", "releases/**" ]
  pull_request:
    branches: [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        # add other deps
        #- uses: actions/foundry-toolchain
        # Set up your build here:
        # -run: forge install
        # -run: yarn
      - run: yarn
      - run: npx thirdweb deploy

  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        # add other deps
        #- uses: actions/foundry-toolchain
        # Set up your build here:
        # -run: forge install
        # -run: yarn
      - run: yarn
      - run: npx thirdweb publish 
